<#
.SYNOPSIS
    Validate (default) or Sync product versions from the single release descriptor.

.DESCRIPTION
    Source of truth: work/phone-deck/release-versions.json
    Default mode is read-only validation. Pass -Sync to regenerate marked props and
    rewrite product version references so they match the descriptor.

    Does not build products, touch packaging scripts, CI, toolchain locks, or signing.
#>
[CmdletBinding()]
param(
    [switch]$Sync,
    [string]$PhoneDeckRoot = '',
    [string]$DescriptorPath = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($PSVersionTable.PSVersion.Major -lt 7) {
    throw "Assert-ReleaseVersions.ps1 requires PowerShell 7+. Current: $($PSVersionTable.PSVersion)"
}

# Windows PE VERSIONINFO / .NET FileVersion uses four 16-bit WORD fields (0..65535).
# windows.sequence and macos.bundleVersion are mapped into the 4th component (revision),
# so they must stay within that WORD limit or the generated FileVersion is invalid.
$MaxFileVersionComponent = 65535
# Google Play / Android versionCode hard upper bound.
$MaxAndroidVersionCode = 2100000000

# Full SemVer 2.0.0, anchored. Rejects whitespace and XML/C# metacharacters by charset.
$SemVerFullPattern = '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
$SemVerCorePattern = '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$'

function Resolve-DefaultPhoneDeckRoot {
    $repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '../..')).Path
    return (Join-Path $repoRoot 'work/phone-deck')
}

if ([string]::IsNullOrWhiteSpace($PhoneDeckRoot)) {
    $PhoneDeckRoot = Resolve-DefaultPhoneDeckRoot
}
$PhoneDeckRoot = [System.IO.Path]::GetFullPath($PhoneDeckRoot)

if ([string]::IsNullOrWhiteSpace($DescriptorPath)) {
    $DescriptorPath = Join-Path $PhoneDeckRoot 'release-versions.json'
}
$DescriptorPath = [System.IO.Path]::GetFullPath($DescriptorPath)

$paths = [ordered]@{
    Descriptor          = $DescriptorPath
    WindowsProps        = Join-Path $PhoneDeckRoot 'windows/Directory.Build.props'
    MacProps            = Join-Path $PhoneDeckRoot 'macos/Directory.Build.props'
    FleetUpdates        = Join-Path $PhoneDeckRoot 'windows/PhoneDeck.Server/FleetUpdates.cs'
    BluetoothReceiver   = Join-Path $PhoneDeckRoot 'windows/PhoneDeck.Server/BluetoothReceiver.cs'
    AndroidGradle       = Join-Path $PhoneDeckRoot 'android/app/build.gradle'
    MacProgram          = Join-Path $PhoneDeckRoot 'macos/PhoneDeck.Receiver/Program.cs'
    MacInfoPlist        = Join-Path $PhoneDeckRoot 'macos/PhoneDeck.Receiver/Packaging/Info.plist'
}

$GeneratedBanner = @'
<!--
  GENERATED FILE — do not edit by hand.
  Source of truth: work/phone-deck/release-versions.json
  Regenerated by: pwsh -File scripts/versioning/Assert-ReleaseVersions.ps1 -Sync
-->
'@

function Test-StrictJsonIntegerType {
    param([AllowNull()]$Value)
    if ($null -eq $Value) { return $false }
    # ConvertFrom-Json: true/false -> Boolean (casts to 1/0); "23" -> String; 23.1 -> Double.
    # Only accept integral CLR types so fractional/bool/string cannot round or coerce.
    if ($Value -is [bool]) { return $false }
    if ($Value -is [string]) { return $false }
    if ($Value -is [double] -or $Value -is [float] -or $Value -is [decimal]) { return $false }
    return (
        $Value -is [byte] -or $Value -is [sbyte] -or
        $Value -is [int16] -or $Value -is [uint16] -or
        $Value -is [int32] -or $Value -is [uint32] -or
        $Value -is [int64] -or $Value -is [uint64]
    )
}

function Assert-StrictJsonInteger {
    param(
        [AllowNull()]$Value,
        [Parameter(Mandatory)][string]$Name,
        [long]$Min = 1,
        [long]$Max = [long]::MaxValue
    )
    if ($null -eq $Value) {
        throw "Missing required field: $Name"
    }
    if (-not (Test-StrictJsonIntegerType -Value $Value)) {
        $typeName = if ($null -eq $Value) { 'null' } else { $Value.GetType().FullName }
        throw "Field $Name must be a JSON integer type (not bool/string/fractional), got type=$typeName value=$Value"
    }
    $n = [long]$Value
    if ($n -lt $Min -or $n -gt $Max) {
        throw "Field $Name must be in [$Min, $Max], got: $n"
    }
    return $n
}

function Assert-SafeSemVer {
    param(
        [AllowNull()]$Value,
        [Parameter(Mandatory)][string]$Name,
        [switch]$CoreOnly
    )
    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string]$Value)) {
        throw "Missing or empty required field: $Name"
    }
    if ($Value -isnot [string]) {
        throw "Field $Name must be a JSON string, got type=$($Value.GetType().FullName)"
    }
    $text = [string]$Value
    # Defense in depth before any C#/XML write: reject control chars and markup/code/MSBuild metacharacters.
    if ($text -match '[\x00-\x1F\x7F<>&"''$(){};%]' -or $text.Contains('\') -or $text.Contains('`')) {
        throw "Field $Name contains unsafe characters for C#/XML embedding: $text"
    }
    $pattern = if ($CoreOnly) { $script:SemVerCorePattern } else { $script:SemVerFullPattern }
    if ($text -notmatch $pattern) {
        $kind = if ($CoreOnly) { 'core SemVer MAJOR.MINOR.PATCH' } else { 'full anchored SemVer 2.0.0' }
        throw "Field $Name must be $kind, got: $text"
    }
    return $text
}

function Assert-NumericBundleString {
    param(
        [AllowNull()]$Value,
        [Parameter(Mandatory)][string]$Name,
        [long]$Max = $script:MaxFileVersionComponent
    )
    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace([string]$Value)) {
        throw "Missing or empty required field: $Name"
    }
    if ($Value -isnot [string]) {
        throw "Field $Name must be a JSON string, got type=$($Value.GetType().FullName)"
    }
    $text = [string]$Value
    if ($text -notmatch '^[1-9]\d*$') {
        throw "Field $Name must be a positive decimal integer string (no leading zeros/sign/fraction), got: $text"
    }
    $n = [long]$text
    if ($n -gt $Max) {
        throw "Field $Name=$n exceeds max $Max (FileVersion WORD component limit when mapped into revision)."
    }
    return $text
}

function Get-NumericVersionPrefix {
    param([Parameter(Mandatory)][string]$MarketingVersion)
    if ($MarketingVersion -notmatch '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)') {
        throw "Cannot derive numeric version prefix from '$MarketingVersion'"
    }
    return "$($Matches[1]).$($Matches[2]).$($Matches[3])"
}

function Assert-FileVersionComponents {
    param(
        [Parameter(Mandatory)][string]$FileVersion,
        [Parameter(Mandatory)][string]$Context
    )
    $parts = $FileVersion.Split('.')
    if ($parts.Count -ne 4) {
        throw "$Context FileVersion must have exactly 4 numeric components, got: $FileVersion"
    }
    foreach ($part in $parts) {
        if ($part -notmatch '^(0|[1-9]\d*)$') {
            throw "$Context FileVersion component '$part' is not a non-negative integer without leading zeros (except 0): $FileVersion"
        }
        $n = [long]$part
        if ($n -gt $script:MaxFileVersionComponent) {
            throw ("$Context FileVersion component $n exceeds $script:MaxFileVersionComponent. " +
                "Windows PE VERSIONINFO / .NET FileVersion fields are 16-bit WORDs (0..65535); " +
                "sequence/bundle revision mapped into the 4th component must stay within that limit. Got: $FileVersion")
        }
    }
}

function Read-Utf8Text {
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Missing required file: $Path"
    }
    return [System.IO.File]::ReadAllText($Path)
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Content
    )
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Get-JsonProperty {
    param(
        [Parameter(Mandatory)]$Object,
        [Parameter(Mandatory)][string]$Name
    )
    if ($null -eq $Object) {
        return $null
    }
    $prop = $Object.PSObject.Properties[$Name]
    if ($null -eq $prop) {
        return $null
    }
    return $prop.Value
}

function Read-ReleaseDescriptor {
    param([Parameter(Mandatory)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Release descriptor not found: $Path"
    }

    try {
        $raw = Get-Content -LiteralPath $Path -Raw -Encoding utf8
        $doc = $raw | ConvertFrom-Json -Depth 32
    } catch {
        throw "Invalid release descriptor JSON ($Path): $($_.Exception.Message)"
    }

    $schema = Assert-StrictJsonInteger -Value (Get-JsonProperty -Object $doc -Name 'schemaVersion') -Name 'schemaVersion' -Min 1 -Max 1
    if ($schema -ne 1) {
        throw "Unsupported schemaVersion=$schema (expected 1)"
    }

    $windows = Get-JsonProperty -Object $doc -Name 'windows'
    $android = Get-JsonProperty -Object $doc -Name 'android'
    $macos = Get-JsonProperty -Object $doc -Name 'macos'
    $console = Get-JsonProperty -Object $doc -Name 'console'
    if ($null -eq $windows) { throw 'Missing required section: windows' }
    if ($null -eq $android) { throw 'Missing required section: android' }
    if ($null -eq $macos) { throw 'Missing required section: macos' }
    if ($null -eq $console) { throw 'Missing required section: console' }

    $windowsVersion = Assert-SafeSemVer -Value (Get-JsonProperty -Object $windows -Name 'version') -Name 'windows.version'
    # Sequence becomes FileVersion revision (4th WORD); enforce 1..65535.
    $windowsSequence = Assert-StrictJsonInteger `
        -Value (Get-JsonProperty -Object $windows -Name 'sequence') `
        -Name 'windows.sequence' `
        -Min 1 `
        -Max $script:MaxFileVersionComponent

    $androidVersionName = Assert-SafeSemVer -Value (Get-JsonProperty -Object $android -Name 'versionName') -Name 'android.versionName'
    $androidCode = Assert-StrictJsonInteger `
        -Value (Get-JsonProperty -Object $android -Name 'versionCode') `
        -Name 'android.versionCode' `
        -Min 1 `
        -Max $script:MaxAndroidVersionCode

    $macVersion = Assert-SafeSemVer -Value (Get-JsonProperty -Object $macos -Name 'version') -Name 'macos.version'
    $macBundleShort = Assert-SafeSemVer -Value (Get-JsonProperty -Object $macos -Name 'bundleShortVersion') -Name 'macos.bundleShortVersion' -CoreOnly
    $macBundleVersion = Assert-NumericBundleString -Value (Get-JsonProperty -Object $macos -Name 'bundleVersion') -Name 'macos.bundleVersion'

    $map = Get-JsonProperty -Object $macos -Name 'historicBundleMapping'
    if ($null -eq $map) {
        throw 'Missing required field: macos.historicBundleMapping (explicit historic Mac mapping required)'
    }
    $mapHealth = Assert-SafeSemVer -Value (Get-JsonProperty -Object $map -Name 'healthVersion') -Name 'macos.historicBundleMapping.healthVersion'
    $mapShort = Assert-SafeSemVer -Value (Get-JsonProperty -Object $map -Name 'bundleShortVersion') -Name 'macos.historicBundleMapping.bundleShortVersion' -CoreOnly
    $mapBundle = Assert-NumericBundleString -Value (Get-JsonProperty -Object $map -Name 'bundleVersion') -Name 'macos.historicBundleMapping.bundleVersion'
    $mapNote = Get-JsonProperty -Object $map -Name 'note'
    if ($null -eq $mapNote -or [string]::IsNullOrWhiteSpace([string]$mapNote)) {
        throw 'Missing or empty required field: macos.historicBundleMapping.note'
    }
    if ($mapNote -isnot [string]) {
        throw "macos.historicBundleMapping.note must be a JSON string, got type=$($mapNote.GetType().FullName)"
    }

    if ($mapHealth -ne $macVersion -or
        $mapShort -ne $macBundleShort -or
        $mapBundle -ne $macBundleVersion) {
        throw 'macos.historicBundleMapping values must match macos.version / bundleShortVersion / bundleVersion'
    }

    $consoleFollows = Get-JsonProperty -Object $console -Name 'follows'
    if ($null -eq $consoleFollows -or [string]::IsNullOrWhiteSpace([string]$consoleFollows)) {
        throw 'Missing or empty required field: console.follows'
    }
    if ($consoleFollows -isnot [string]) {
        throw "console.follows must be a JSON string, got type=$($consoleFollows.GetType().FullName)"
    }
    if ([string]$consoleFollows -ne 'windows.version') {
        throw "console.follows must be 'windows.version' in schemaVersion=1"
    }
    $consoleInfo = Assert-SafeSemVer -Value (Get-JsonProperty -Object $console -Name 'informationalVersion') -Name 'console.informationalVersion'
    if ($consoleInfo -ne $windowsVersion) {
        throw 'console.informationalVersion must equal windows.version'
    }

    $winNumeric = Get-NumericVersionPrefix -MarketingVersion $windowsVersion
    $macNumeric = Get-NumericVersionPrefix -MarketingVersion $macVersion
    Assert-FileVersionComponents -FileVersion "$winNumeric.$windowsSequence" -Context 'windows'
    Assert-FileVersionComponents -FileVersion "$macNumeric.$macBundleVersion" -Context 'macos'
    Assert-FileVersionComponents -FileVersion "$macBundleShort.0" -Context 'macos AssemblyVersion'

    return [pscustomobject]@{
        SchemaVersion = $schema
        WindowsVersion = $windowsVersion
        WindowsSequence = $windowsSequence
        WindowsNumeric = $winNumeric
        AndroidVersionName = $androidVersionName
        AndroidVersionCode = $androidCode
        MacVersion = $macVersion
        MacNumeric = $macNumeric
        MacBundleShortVersion = $macBundleShort
        MacBundleVersion = $macBundleVersion
        ConsoleInformationalVersion = $consoleInfo
    }
}

function Get-SourceSnapshot {
    param([Parameter(Mandatory)]$Paths)

    $fleet = Read-Utf8Text -Path $Paths.FleetUpdates
    if ($fleet -notmatch 'internal const string Version = "([^"]+)"') {
        throw "Could not read FleetUpdates.Version from $($Paths.FleetUpdates)"
    }
    $fleetVersion = $Matches[1]
    if ($fleet -notmatch 'internal const long Sequence = (\d+)') {
        throw "Could not read FleetUpdates.Sequence from $($Paths.FleetUpdates)"
    }
    $fleetSequence = [long]$Matches[1]

    $bt = Read-Utf8Text -Path $Paths.BluetoothReceiver
    if ($bt -notmatch '(?s)private static void SendHello\b.*?version = "([^"]+)"') {
        throw "Could not read BluetoothReceiver hello version from $($Paths.BluetoothReceiver)"
    }
    $btVersion = $Matches[1]

    $gradle = Read-Utf8Text -Path $Paths.AndroidGradle
    if ($gradle -notmatch 'versionCode\s+(\d+)') {
        throw "Could not read android versionCode from $($Paths.AndroidGradle)"
    }
    $androidCode = [long]$Matches[1]
    if ($gradle -notmatch 'versionName\s+"([^"]+)"') {
        throw "Could not read android versionName from $($Paths.AndroidGradle)"
    }
    $androidName = $Matches[1]

    $macProgram = Read-Utf8Text -Path $Paths.MacProgram
    if ($macProgram -notmatch '(?m)^\s*version = "([^"]+)",\s*$') {
        throw "Could not read macOS health version from $($Paths.MacProgram)"
    }
    $macHealth = $Matches[1]

    $plist = Read-Utf8Text -Path $Paths.MacInfoPlist
    if ($plist -notmatch '(?s)<key>CFBundleShortVersionString</key>\s*<string>([^<]+)</string>') {
        throw "Could not read CFBundleShortVersionString from $($Paths.MacInfoPlist)"
    }
    $bundleShort = $Matches[1].Trim()
    if ($plist -notmatch '(?s)<key>CFBundleVersion</key>\s*<string>([^<]+)</string>') {
        throw "Could not read CFBundleVersion from $($Paths.MacInfoPlist)"
    }
    $bundleVersion = $Matches[1].Trim()

    $winProps = $null
    $macProps = $null
    if (Test-Path -LiteralPath $Paths.WindowsProps) {
        $winProps = Read-Utf8Text -Path $Paths.WindowsProps
    }
    if (Test-Path -LiteralPath $Paths.MacProps) {
        $macProps = Read-Utf8Text -Path $Paths.MacProps
    }

    return [pscustomobject]@{
        FleetVersion = $fleetVersion
        FleetSequence = $fleetSequence
        BluetoothVersion = $btVersion
        AndroidVersionCode = $androidCode
        AndroidVersionName = $androidName
        MacHealthVersion = $macHealth
        MacBundleShortVersion = $bundleShort
        MacBundleVersion = $bundleVersion
        WindowsPropsText = $winProps
        MacPropsText = $macProps
    }
}

function New-WindowsPropsContent {
    param([Parameter(Mandatory)]$Descriptor)
    $numeric = $Descriptor.WindowsNumeric
    $fileVersion = "$numeric.$($Descriptor.WindowsSequence)"
    Assert-FileVersionComponents -FileVersion $fileVersion -Context 'windows generated'
    Assert-FileVersionComponents -FileVersion "$numeric.0" -Context 'windows AssemblyVersion'
    # Values already passed Assert-SafeSemVer / strict int; still refuse markup before XML write.
    foreach ($piece in @($numeric, $fileVersion, $Descriptor.WindowsVersion, [string]$Descriptor.WindowsSequence)) {
        if ($piece -match '[<>&"''$(){};%]') {
            throw "Refusing to write unsafe token into windows Directory.Build.props: $piece"
        }
    }
    return @"
$GeneratedBanner
<Project>
  <PropertyGroup>
    <Version>$numeric</Version>
    <AssemblyVersion>$numeric.0</AssemblyVersion>
    <FileVersion>$fileVersion</FileVersion>
    <InformationalVersion>$($Descriptor.WindowsVersion)</InformationalVersion>
    <PhoneDeckReleaseSequence>$($Descriptor.WindowsSequence)</PhoneDeckReleaseSequence>
  </PropertyGroup>
</Project>
"@
}

function New-MacPropsContent {
    param([Parameter(Mandatory)]$Descriptor)
    $numeric = $Descriptor.MacNumeric
    $fileVersion = "$numeric.$($Descriptor.MacBundleVersion)"
    Assert-FileVersionComponents -FileVersion $fileVersion -Context 'macos generated'
    Assert-FileVersionComponents -FileVersion "$($Descriptor.MacBundleShortVersion).0" -Context 'macos AssemblyVersion'
    foreach ($piece in @($Descriptor.MacBundleShortVersion, $fileVersion, $Descriptor.MacVersion, $Descriptor.MacBundleVersion)) {
        if ($piece -match '[<>&"''$(){};%]') {
            throw "Refusing to write unsafe token into macos Directory.Build.props: $piece"
        }
    }
    return @"
$GeneratedBanner
<Project>
  <PropertyGroup>
    <Version>$($Descriptor.MacBundleShortVersion)</Version>
    <AssemblyVersion>$($Descriptor.MacBundleShortVersion).0</AssemblyVersion>
    <FileVersion>$fileVersion</FileVersion>
    <InformationalVersion>$($Descriptor.MacVersion)</InformationalVersion>
    <PhoneDeckBundleVersion>$($Descriptor.MacBundleVersion)</PhoneDeckBundleVersion>
  </PropertyGroup>
</Project>
"@
}

function Read-PropsXml {
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Label
    )
    try {
        $settings = New-Object System.Xml.XmlReaderSettings
        $settings.DtdProcessing = [System.Xml.DtdProcessing]::Prohibit
        $settings.XmlResolver = $null
        $reader = [System.Xml.XmlReader]::Create([System.IO.StringReader]::new($Text), $settings)
        $xml = New-Object System.Xml.XmlDocument
        $xml.XmlResolver = $null
        $xml.Load($reader)
        $reader.Dispose()
        return $xml
    } catch {
        throw "$Label is missing, invalid, or unsafe XML: $($_.Exception.Message)"
    }
}

function Get-RequiredUniquePropsValue {
    param(
        [Parameter(Mandatory)]$Xml,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)]$Drift
    )
    $nodes = $Xml.SelectNodes("//*[local-name()='$Name']")
    if ($null -eq $nodes -or $nodes.Count -eq 0) {
        [void]$Drift.Add("$Label missing <$Name>")
        return $null
    }
    if ($nodes.Count -gt 1) {
        [void]$Drift.Add("$Label has duplicate <$Name> count=$($nodes.Count)")
        return $null
    }
    return ([string]$nodes.Item(0).InnerText).Trim()
}

function Compare-PropsDocument {
    param(
        [AllowNull()][string]$Text,
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)]$Expected,
        [Parameter(Mandatory)]$Drift
    )
    if ($null -eq $Text) {
        [void]$Drift.Add("Missing generated $Label")
        return
    }
    if ($Text -notmatch 'GENERATED FILE') {
        [void]$Drift.Add("$Label is missing GENERATED FILE marker")
    }
    try {
        $xml = Read-PropsXml -Text $Text -Label $Label
    } catch {
        [void]$Drift.Add([string]$_.Exception.Message)
        return
    }

    $actual = @{}
    foreach ($name in @($Expected.Keys)) {
        $actual[$name] = Get-RequiredUniquePropsValue -Xml $xml -Name ([string]$name) -Label $Label -Drift $Drift
    }
    foreach ($name in @($Expected.Keys)) {
        if ($null -eq $actual[$name]) { continue }
        if ($actual[$name] -ne [string]$Expected[$name]) {
            [void]$Drift.Add("$Label <$name>='$($actual[$name])' != expected '$($Expected[$name])'")
        }
    }
}

function Compare-Expected {
    param(
        [Parameter(Mandatory)]$Descriptor,
        [Parameter(Mandatory)]$Actual
    )

    $drift = New-Object System.Collections.Generic.List[string]

    if ($Actual.FleetVersion -ne $Descriptor.WindowsVersion) {
        [void]$drift.Add("FleetUpdates.Version='$($Actual.FleetVersion)' != windows.version='$($Descriptor.WindowsVersion)'")
    }
    if ($Actual.FleetSequence -ne $Descriptor.WindowsSequence) {
        [void]$drift.Add("FleetUpdates.Sequence=$($Actual.FleetSequence) != windows.sequence=$($Descriptor.WindowsSequence)")
    }
    if ($Actual.BluetoothVersion -ne $Descriptor.WindowsVersion) {
        [void]$drift.Add("BluetoothReceiver hello version='$($Actual.BluetoothVersion)' != windows.version='$($Descriptor.WindowsVersion)'")
    }
    if ($Actual.AndroidVersionName -ne $Descriptor.AndroidVersionName) {
        [void]$drift.Add("android versionName='$($Actual.AndroidVersionName)' != '$($Descriptor.AndroidVersionName)'")
    }
    if ($Actual.AndroidVersionCode -ne $Descriptor.AndroidVersionCode) {
        [void]$drift.Add("android versionCode=$($Actual.AndroidVersionCode) != $($Descriptor.AndroidVersionCode)")
    }
    if ($Actual.MacHealthVersion -ne $Descriptor.MacVersion) {
        [void]$drift.Add("macOS health version='$($Actual.MacHealthVersion)' != macos.version='$($Descriptor.MacVersion)'")
    }
    if ($Actual.MacBundleShortVersion -ne $Descriptor.MacBundleShortVersion) {
        [void]$drift.Add("CFBundleShortVersionString='$($Actual.MacBundleShortVersion)' != '$($Descriptor.MacBundleShortVersion)'")
    }
    if ($Actual.MacBundleVersion -ne $Descriptor.MacBundleVersion) {
        [void]$drift.Add("CFBundleVersion='$($Actual.MacBundleVersion)' != '$($Descriptor.MacBundleVersion)'")
    }

    $expectedWin = @{
        Version                   = $Descriptor.WindowsNumeric
        AssemblyVersion           = "$($Descriptor.WindowsNumeric).0"
        FileVersion               = "$($Descriptor.WindowsNumeric).$($Descriptor.WindowsSequence)"
        InformationalVersion      = $Descriptor.WindowsVersion
        PhoneDeckReleaseSequence  = [string]$Descriptor.WindowsSequence
    }
    Compare-PropsDocument -Text $Actual.WindowsPropsText -Label 'windows/Directory.Build.props' -Expected $expectedWin -Drift $drift

    # Console follows windows.version via the same InformationalVersion field already compared above.
    if ($Descriptor.ConsoleInformationalVersion -ne $Descriptor.WindowsVersion) {
        [void]$drift.Add("console.informationalVersion '$($Descriptor.ConsoleInformationalVersion)' != windows.version '$($Descriptor.WindowsVersion)'")
    }

    $expectedMac = @{
        Version                = $Descriptor.MacBundleShortVersion
        AssemblyVersion        = "$($Descriptor.MacBundleShortVersion).0"
        FileVersion            = "$($Descriptor.MacNumeric).$($Descriptor.MacBundleVersion)"
        InformationalVersion   = $Descriptor.MacVersion
        PhoneDeckBundleVersion = $Descriptor.MacBundleVersion
    }
    Compare-PropsDocument -Text $Actual.MacPropsText -Label 'macos/Directory.Build.props' -Expected $expectedMac -Drift $drift

    # Comma prevents PowerShell from enumerating the list on return.
    return ,$drift
}

function Sync-ProductSources {
    param(
        [Parameter(Mandatory)]$Descriptor,
        [Parameter(Mandatory)]$Paths
    )

    Write-Utf8NoBom -Path $Paths.WindowsProps -Content (New-WindowsPropsContent -Descriptor $Descriptor)
    Write-Utf8NoBom -Path $Paths.MacProps -Content (New-MacPropsContent -Descriptor $Descriptor)

    $fleet = Read-Utf8Text -Path $Paths.FleetUpdates
    $fleet2 = [regex]::Replace($fleet, 'internal const string Version = "[^"]+"', "internal const string Version = `"$($Descriptor.WindowsVersion)`"", 1)
    $fleet2 = [regex]::Replace($fleet2, 'internal const long Sequence = \d+', "internal const long Sequence = $($Descriptor.WindowsSequence)", 1)
    if ($fleet2 -eq $fleet -and ($fleet -notmatch [regex]::Escape($Descriptor.WindowsVersion) -or $fleet -notmatch "Sequence = $($Descriptor.WindowsSequence)")) {
        throw 'Failed to sync FleetUpdates.cs version/sequence'
    }
    Write-Utf8NoBom -Path $Paths.FleetUpdates -Content $fleet2

    $bt = Read-Utf8Text -Path $Paths.BluetoothReceiver
    $bt2 = [regex]::Replace(
        $bt,
        '(?s)(private static void SendHello\b.*?version = ")[^"]+(")',
        "`${1}$($Descriptor.WindowsVersion)`${2}",
        1
    )
    if ($bt2 -eq $bt -and $bt -notmatch [regex]::Escape("version = `"$($Descriptor.WindowsVersion)`"")) {
        throw 'Failed to sync BluetoothReceiver hello version'
    }
    Write-Utf8NoBom -Path $Paths.BluetoothReceiver -Content $bt2

    $gradle = Read-Utf8Text -Path $Paths.AndroidGradle
    $gradle2 = [regex]::Replace($gradle, 'versionCode\s+\d+', "versionCode $($Descriptor.AndroidVersionCode)", 1)
    $gradle2 = [regex]::Replace($gradle2, 'versionName\s+"[^"]+"', "versionName `"$($Descriptor.AndroidVersionName)`"", 1)
    Write-Utf8NoBom -Path $Paths.AndroidGradle -Content $gradle2

    $macProgram = Read-Utf8Text -Path $Paths.MacProgram
    $macProgram2 = [regex]::Replace(
        $macProgram,
        '(?m)^(\s*version = ")[^"]+(",\s*)$',
        "`${1}$($Descriptor.MacVersion)`${2}",
        1
    )
    Write-Utf8NoBom -Path $Paths.MacProgram -Content $macProgram2

    $plist = Read-Utf8Text -Path $Paths.MacInfoPlist
    $plist2 = [regex]::Replace(
        $plist,
        '(?s)(<key>CFBundleShortVersionString</key>\s*<string>)[^<]+(</string>)',
        "`${1}$($Descriptor.MacBundleShortVersion)`${2}",
        1
    )
    $plist2 = [regex]::Replace(
        $plist2,
        '(?s)(<key>CFBundleVersion</key>\s*<string>)[^<]+(</string>)',
        "`${1}$($Descriptor.MacBundleVersion)`${2}",
        1
    )
    Write-Utf8NoBom -Path $Paths.MacInfoPlist -Content $plist2
}

# --- main ---
$descriptor = Read-ReleaseDescriptor -Path $paths.Descriptor

if ($Sync) {
    Sync-ProductSources -Descriptor $descriptor -Paths $paths
    Write-Host "Synced product version references and generated props from $DescriptorPath"
}

$actual = Get-SourceSnapshot -Paths $paths
$drift = Compare-Expected -Descriptor $descriptor -Actual $actual

if ($drift.Count -gt 0) {
    Write-Host 'Release version drift detected:' -ForegroundColor Red
    foreach ($item in $drift) {
        Write-Host "  - $item" -ForegroundColor Red
    }
    if (-not $Sync) {
        Write-Host "Default mode is validate-only. Re-run with -Sync to regenerate from $DescriptorPath" -ForegroundColor Yellow
    }
    exit 1
}

Write-Host "OK: release versions consistent with $DescriptorPath"
exit 0
